-- Part A --

--1
SELECT * FROM DEPOSIT

--2
SELECT * FROM BORROW

--3
SELECT * FROM CUSTOMERS

--4
INSERT INTO BORROW VALUES (550,'JAY','AJNI',NULL)

--5
SELECT ACTNO, CNAME, AMOUNT FROM DEPOSIT

--6
SELECT LOANNO, AMOUNT FROM BORROW

--7
SELECT * FROM BORROW WHERE BNAME = 'ANDHERI'

--8
SELECT ACTNO, AMOUNT FROM DEPOSIT WHERE ACTNO = 106

--9
SELECT CNAME FROM BORROW WHERE AMOUNT > 5000

--10
SELECT CNAME FROM DEPOSIT WHERE ADATE > '1996-12-01'

--11
SELECT CNAME FROM DEPOSIT WHERE ACTNO < 105

--12
SELECT CNAME FROM CUSTOMERS WHERE CITY = 'NAGPUR' OR CITY = 'DELHI'

SELECT CNAME FROM CUSTOMERS WHERE CITY IN ('NAGPUR','DELHI')

--13
SELECT CNAME, BNAME FROM DEPOSIT WHERE AMOUNT > 4000 AND ACTNO < 105

--14
SELECT CNAME FROM BORROW WHERE AMOUNT >= 3000 AND AMOUNT <= 8000

SELECT CNAME FROM BORROW WHERE AMOUNT  BETWEEN 3000 AND 8000

--15
SELECT CNAME FROM DEPOSIT WHERE BNAME != 'ANDHERI'

--16
SELECT ACTNO, CNAME, AMOUNT FROM DEPOSIT WHERE BNAME IN ('AJNI','KAROLBAGH', 'M.G. ROAD') AND ACTNO < 104

--17
SELECT TOP 5 * FROM CUSTOMERS

--18
SELECT TOP 3 * FROM DEPOSIT WHERE AMOUNT > 1000

--19
SELECT TOP 5 LOANNO, CNAME FROM BORROW WHERE BNAME != 'ANDHERI'

--20
SELECT DISTINCT CITY FROM CUSTOMERS

--21
SELECT DISTINCT BNAME FROM BRANCH

--22
SELECT * FROM CUSTOMERS ORDER BY CITY ASC

--23
SELECT * FROM DEPOSIT ORDER BY AMOUNT DESC

--24
UPDATE DEPOSIT SET AMOUNT = 5000 WHERE AMOUNT = 3000

SELECT * FROM DEPOSIT

--25
UPDATE BORROW SET BNAME = 'C.G. ROAD' WHERE CNAME = 'ANIL' 

SELECT * FROM BORROW

--26
UPDATE DEPOSIT SET ACTNO = 111, AMOUNT = 5000 WHERE CNAME = 'SANDIP'

SELECT * FROM DEPOSIT

--27
UPDATE BORROW SET AMOUNT = (AMOUNT*0.1)+AMOUNT

SELECT * FROM BORROW

--28
UPDATE DEPOSIT SET AMOUNT = 5000 WHERE ACTNO BETWEEN 103 AND 107

--29
UPDATE BORROW SET AMOUNT = NULL WHERE LOANNO = 321

--30

SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL

--Part B

--1
SELECT RollNo,Name FROM STUDENT WHERE RollNo > 103 AND Backlog > 0

--2
SELECT Name FROM STUDENT WHERE SPI BETWEEN 8 AND 9 AND Branch ='CE' OR Branch ='IT'

--3
SELECT Name FROM STUDENT WHERE Branch != 'CE'

--4
SELECT TOP 3 RollNo,Name FROM STUDENT

--5
SELECT TOP 3 RollNo,Name FROM STUDENT WHERE SPI > 8.5

--6
SELECT DISTINCT City FROM STUDENT

--7
SELECT DISTINCT Branch FROM STUDENT

--8
SELECT * FROM STUDENT 
ORDER BY Backlog DESC

SELECT * FROM STUDENT 
ORDER BY SPI

--9
UPDATE STUDENT SET Branch = 'MCA', City = 'Jamangar' WHERE RollNo=106

--10
UPDATE STUDENT SET Backlog = NULL WHERE Name IN ('Keyur','Bhoomi')

--11
SELECT Name FROM STUDENT WHERE Backlog IS NULL OR Backlog > 1 AND Branch In('CE','IT')

