--Part A

--1
SELECT e.EmpName FROM EMPLOYEE e WHERE e.Salary > 13000 AND e.City IN ('Rajkot','Baroda')

--2
SELECT * FROM EMPLOYEE
ORDER BY EmpName ASC

--3
SELECT DISTINCT e.City FROM EMPLOYEE e

--4
UPDATE EMPLOYEE SET City = NULL WHERE EmpName IN ('Keyur','Bhoomi')

--5
SELECT e.EmpName FROM EMPLOYEE e WHERE e.City IS NULL

--6
DELETE EMPLOYEE WHERE Salary >= 14000

--7
DELETE EMPLOYEE WHERE City = 'Rajkot'

--8
DELETE EMPLOYEE WHERE JoiningDate > '2007-1-1'

--9
TRUNCATE TABLE EMPLOYEE

--10
DROP TABLE EMPLOYEE

--11
TRUNCATE TABLE DEPOSIT

--12
DROP TABLE DEPOSIT

--13
DROP TABLE BRANCH

--14
DROP TABLE CUSTOMERS

--15
DROP TABLE BORROW

--Part B

--1
SELECT DISTINCT a.BNAME FROM ACCOUNT a

--2
SELECT CNAME FROM ACCOUNT
ORDER BY AMOUNT , CNAME DESC

--3
UPDATE ACCOUNT SET BNAME = NULL WHERE CNAME IN ('Anil','Shivani')

--4
SELECT a.CNAME FROM ACCOUNT a WHERE a.BNAME IS NULL

--5
DELETE ACCOUNT WHERE AMOUNT >= 4000

--6
DELETE ACCOUNT WHERE BNAME = 'CHANDI'

--7
DELETE ACCOUNT WHERE ADATE > '1995-1-10'

--8
TRUNCATE TABLE ACCOUNT

--9
DROP TABLE ACCOUNT


--Part C

--1
SELECT a.CNAME FROM ACCOUNT a WHERE a.BNAME IN ('AJNI','CHANDI') AND a.AMOUNT > 3000
ORDER BY a.AMOUNT,a.CNAME DESC

--2 
SELECT DISTINCT TOP 3 a.BNAME FROM ACCOUNT a 
ORDER BY a.BNAME

--3
SELECT a.CNAME FROM ACCOUNT a WHERE a.ACTNO > 103
ORDER BY a.AMOUNT,a.CNAME DESC

--4
UPDATE ACCOUNT SET BNAME= NULL WHERE CNAME IN ('Anil','Mehul')

--5
SELECT a.CNAME FROM ACCOUNT a WHERE a.BNAME IS NULL

--6
UPDATE ACCOUNT SET AMOUNT = 5000 WHERE CNAME = 'Anil'

--7
UPDATE ACCOUNT SET AMOUNT = NULL WHERE ACTNO = 109

--8
SELECT * FROM ACCOUNT
ORDER BY BNAME DESC

--9
TRUNCATE TABLE ACCOUNT

--10
DROP TABLE ACCOUNT

