import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: "100"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} box-border w-dvw h-dvh`}
      >
        <div className='w-full h-full p-5'>
          <div className='border p-4 border-gray-300 h-full'>
            <div className='h-full flex flex-row'>
                {children}
            </div>
          </div>
        </div>

      </body>
    </html>
  );
}
